{-# LANGUAGE TemplateHaskell, OverloadedStrings #-}

module Main where

import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as L
import Data.FileEmbed
import System.Directory
import System.Environment
import Text.Blaze.Html5 hiding (html)
import qualified Text.Blaze.Html5 as H
import Text.Blaze.Html5.Attributes
import Text.Blaze.Html.Renderer.Utf8

main :: IO ()
main = do
    [path] <- getArgs
    let css = $(embedFile "static/main.css")
    createDirectory path
    B.writeFile (path ++ "/main.css") css
    L.writeFile (path ++ "/index.html") $ renderHtml html

html :: Html
html = docTypeHtml $ do
    H.head $ do
        link ! rel "stylesheet" ! type_ "text/css" ! href "./main.css"
    body ! class_ "hoge" $ do
        h1 "generated by blaze-html"
